# Site settings
title: Noemi's Profile
email: noemiderzsy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my page!
baseurl: "/patchwork-gh-pages-24"
url: "http://nderzsy.github.io"
twitter_username: NoemiDerzsy
github_username:  nderzsy
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
